### ISSUE TITLE
_decode_lstm ctx2out

### ISSUE THREAD

**Issue by arieling** [yunjey/show-attend-and-tell-tensorflow#17]
Document indicates that ctx2out is in Eq(2).  I can't find corresponding ctx2out in the paper. Can you give me some insight about why we need that?

**Comment by yunjey** [comment]
The paper on arXiv has been revised so that you are probably confused. Now, it's not Eq(2) but Eq(7).

![ls](https://cloud.githubusercontent.com/assets/15663219/23575857/01cbcd1c-00d8-11e7-879d-fa033da56be7.png)

Comparing above equation and the code, prev2out corresponds to red line and ctx2out corresponds to blue line. This is a skip connection.
