### ISSUE TITLE
Error while running evaluate_model 

### ISSUE THREAD

**Issue by Arora90** [yunjey/show-attend-and-tell-tensorflow#6]
Hello, yunjey, thanks a lot for writing such a well structured code.

I got an error while running evaluate_model code. At solver.test(data, split='val'), code throws the following error :  Assign requires shapes of both tensors to match. lhs shape= [1500] rhs shape= [1024]

Here I have following doubts:

1. Hidden state size in training and testing is not same(1024, 1500). when i changed the hidden state size to 1024, I got a similar error.

2. Testing model path  = './model/lstm3/model-18' does not exist,  should it be './model/lstm/model-18' or './model/lstm/model-10' as done while training the model.

Till now I had done following steps:

 - 1. Obtained VGG features for 10 percent of the training data by adding the below lines in prepro.py at line 150.
    train_cutoff = int(0.1 * len(train_dataset))
    print 'Finished processing caption data'
    save_pickle(train_dataset[:train_cutoff], 'data/train/train.annotations.pkl')

 - 2. Trained the model for 20 epochs with VGG feature vector of size=[196, 512], word embedding size =512,  hidden state size =1024, trained model path  = 'model/lstm/', test_model='model/lstm/model-10' as done in the code.

- 3. Converted evaluate_model.ipynb into evaluate_model.py and ran the code with VGG feature vector of size=[196, 512], word embedding size =512,  hidden state size =1500, trained model path  = 'model/lstm/', test_model='./model/lstm3/model-18' as done in the code.    

Thanks in advance for your support.

**Comment by yunjey** [comment]
Arora,
You should use same settings in CaptioningModel and CaptioningSolver for training and evaluating the model. For example, if you assign 1024 as hidden state size in train.py then hidden state size in evaluate_model.ipynb must be equal to 1024 (Model architecture for training and evaluating should be same).

Additionally, if you assign save_every=1 in train.py then model's parameters will be saved in model path for every training epoch. Therefore, when you trained model with 20 epochs, final model is 'model/lstm/model-20'. In other words, test_model in evaluate_model.ipynb should be 'model/lstm/model-20'. (Note that it is possible to use test_model='model/lstm/model-19' in evaluate_model.ipynb because model-19 wil be saved during training')

**Comment by Arora90** [comment]
Thanks you. I am now able to view attention visualizations on MSCOCO validation dataset.
